- name: Configure web servers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: copy nginx conf file to server
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'

    - name: create link to nginx config file to enable it
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Generate index.html file from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'

    - name: reload nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: true
